device: cpu
train:
  batch_size: 128
  train_epochs: 100
  clip: 1.0
model:
  encoder:
    emb_dim: 256
    hid_dim: 512
    n_layers: 2
    dropout: 0.5
  decoder:
    emb_dim: 256
    hid_dim: 512
    n_layers: 2
    dropout: 0.5